### ISSUE TITLE
Importing .mat files into python

### ISSUE THREAD

**Issue by charbiso** [NickThorne123/pydemo#5]
- [x] Import .mat file into python
- [x] Convert into dataframe using pandas
- [x] Rearrange so it's readable
- [x] Run basic descriptives on the data

**Comment by NickThorne123** [comment]
Hi @charbiso , how is this going ?

**Comment by charbiso** [comment]
At the moment I'm writing a script to 1) import the data from every subject, 2) extract their demographics like age and gender, then 3) compile the demographics into one dataframe then run descriptive statistics. I've managed to figure out 2) for individual participants and I think I'm almost there with 1), so will work on that and compiling everything today!

**Comment by charbiso** [comment]
Done!
